namespace ExcelStreamReaderConsole;

public enum VehicleTypeEnum
{
    Motorcycle = 1,
    Car = 2,
    Bus = 3,
    Truck = 4,
    Camper = 5,
    LongBus = 6,
    HeavyTruck = 7,
    Tractor = 8,
    Trailer = 9,
    Undefined = 10000,
    CarWithTrailer = 10009,
    MaritimeMuseum = 10011,
    Government = 10012,
    SpecialServices = 10013,
    Disabled = 10014,
    TouristAgreement = 10015,
    NotOpened = 10016,
    Fault = 10017,
    ElectricCar = 10018
}

public enum PaymentOptionsEnum
{
    Bill = 1,
    Pos = 2,
    Any = 3
}

public enum UsersLogActionEnum
{
    Unknown = 0,
    LoginOK = 1,
    LoginDenied = 2,
    Logout = 3,
    InsertRow = 4,
    UpdateRow = 5,
    DeleteRow = 6,
    CoinBalanceSettingsChanged = 7,
    AllowedDenomsUnder10Changed = 8,
    AllowedDenomsUnder20Changed = 9,
    AllowedDenomsOver20Changed = 10,
    AdminAposPasswordChanged = 11,
    UserAposIntervalsChanged = 12,
    VatChanged = 13,
    PriceRateParamsChanged = 14,
    PriceRateInfoChanged = 15,
    ReceiptHeaderChanged = 16,
    NotificationEmailsChanged = 17,
    RepositorySettingsChanged = 18,
    FinancialQueryPerformed = 19,
    FinancialQueryExported = 20,
    PaymentReceiptRemotePrinted = 21,
    WithdrawalReceiptRemotePrinted = 22,
    DepositReceiptRemotePrinted = 23,
    StateReceiptRemotePrinted = 24,
    PaymentRestrictionsChanged = 25,
    StateReceiptLocalPrinted = 26,
    DepositReceiptLocalPrinted = 27,
    WithdrawalReceiptLocalPrinted = 28,
    PaymentLocalRemotePrinted = 30,
    BalanceReceiptLocalPrinted = 31,
    PaymentLocalLocalPrinted = 32,
    BalanceReceiptRemotePrinted = 33,
    GetListError = 34,
    GetSingleError = 35,
    ImpersonatorLoginOk = 36,
    ImpersonatorLoginFailed = 37,
    EmailSendError = 38,
    ExportFailed = 39,
    ExportUITable = 40,
    UserPasswordChanged = 41,
    GeneralSettingsChanged = 42,
    UserAposTextsChanged = 43,
    DispenseErrorLocalPrinted = 44,
    DispenseErrorRemotePrinted = 45,
    CameraSettingsUpdate = 46,
    RestartError = 47,
    Restart = 48,
    UpdateLaunched = 49,
    UptModuleCommandSend = 50,
    TriggerBtnClicked = 51,
    OpenBarrierMsgSend = 52,
    PlateMsgSend = 53,
    PlateAndOpenBarrierMsgSend = 54,
    KeepBarrierOpenMsgSend = 55,
    KeepBarrierClosedMsgSend = 56,
    KeepBarrierAutoMsgSend = 57,
    InsertFailed = 58,
    UpdateFailed = 59,
    DeleteFailed = 60,
    SynchronizationDeleteRow = 61,
    SynchronizationInsertRow = 62
}